//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyPokerHUD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PokerStars")]
        public string PokerStarsAppName {
            get {
                return ((string)(this["PokerStarsAppName"]));
            }
            set {
                this["PokerStarsAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("888poker")]
        public string EEEPokerAppName {
            get {
                return ((string)(this["EEEPokerAppName"]));
            }
            set {
                this["EEEPokerAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PokerStars")]
        public string PokerStarsFolder {
            get {
                return ((string)(this["PokerStarsFolder"]));
            }
            set {
                this["PokerStarsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("888poker")]
        public string EEEPokerFolder {
            get {
                return ((string)(this["EEEPokerFolder"]));
            }
            set {
                this["EEEPokerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HandHistory")]
        public string PokerStarsHandFolder {
            get {
                return ((string)(this["PokerStarsHandFolder"]));
            }
            set {
                this["PokerStarsHandFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HandHistory")]
        public string EEEPokerHandsFolder {
            get {
                return ((string)(this["EEEPokerHandsFolder"]));
            }
            set {
                this["EEEPokerHandsFolder"] = value;
            }
        }
    }
}
